# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-19 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de terminar')),
            ],
            options={
                'ordering': ['hora_inicio'],
                'verbose_name_plural': 'Horario disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicial')),
                ('hora_final', models.TimeField(verbose_name='Hora final')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de personas')),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalaReuniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicaci\xf3n')),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('nd', 'No disponible'), ('d', 'Disponible'), ('r', 'Reservada'), ('c', 'Confirmada')], default='d', max_length=20)),
                ('horario_disponibilidad', models.ManyToManyField(to='sala_reuniones.HorarioDisponibilidad')),
                ('insumos', models.ManyToManyField(blank=True, default=['Proyector', 'Pizarr\xf3n'], to='sala_reuniones.Insumo')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Sala de reuniones',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala_reuniones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_reuniones.SalaReuniones'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
