# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_reuniones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salareuniones',
            name='estado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('nd', 'No disponible'), ('d', 'Disponible'), ('r', 'Reservada'), ('c', 'Confirmada')], default='d', max_length=20),
        ),
    ]
