# Generated by Django 3.2.6 on 2022-01-06 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_reuniones', '0002_auto_20190120_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'sala_reuniones']},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala_reuniones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sala_reuniones.salareuniones'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
