# Generated by Django 3.2.6 on 2022-01-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_reuniones', '0003_auto_20220106_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='capacidad',
            field=models.IntegerField(default=10, verbose_name='Capacidad de personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala_reuniones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sala_reuniones.salareuniones'),
        ),
    ]
